---
server:
  port: 8080

# https://github.com/Netflix/Hystrix/wiki/Configuration

hystrix:
  command:
    SimpleControlledFailCommand:
      circuitBreaker:
        errorThresholdPercentage: 50
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  stream:
    queue:
      send-id: false
    
  